IT/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings

from Assets.views import tables_laptop_view, tables_staffs_view, dashboard_view, tables_owners_view, login_view, \
    logout_view

app_name = 'it_assets'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('tables/laptops', tables_laptop_view, name='table_laptops_view'),
    url('tables/owners', tables_owners_view, name='table_owners_view'),
    url('tables/staffs', tables_staffs_view, name='table_staffs_view'),
    url('dashboard/', dashboard_view, name='dashboard_view'),
    url('login/', login_view, name='login_view'),
    url('logout/', logout_view, name='logout_view'),
]
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Assets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.db.models import PROTECT


class Laptops(models.Model):
    class Meta:
        verbose_name = 'Laptops'
        verbose_name_plural = 'Laptops'

    id = models.CharField(verbose_name='Laptop ID', null=False, primary_key=True, max_length=30)
    model = models.CharField(verbose_name='Model', null=False, max_length=20)
    ram = models.IntegerField(verbose_name='RAM', null=True)
    SSD_512 = 1
    SSD_256 = 2
    HDD_1T = 3
    HDD_512 = 4
    HDD = (
        (SSD_512, 'SSD 512'),
        (SSD_256, 'SSD_256'),
        (HDD_1T, 'HDD_1T'),
        (HDD_512, 'HDD_512'),
    )
    HDD_status = models.IntegerField(choices=HDD, verbose_name='Hard Model')

    Win_7_32 = 1
    Win_7_64 = 2
    Win_8 = 3
    Win_10 = 4
    Win = (
        (Win_7_32, 'Windows 7 32 bit'),
        (Win_7_64, 'Windows 7 64 bit'),
        (Win_8, 'Windows 8 '),
        (Win_10, 'Windows_10'),
    )
    Win_status = models.IntegerField(choices=Win, verbose_name='Windows Status')

    Laptop_stock = 1
    Laptop_inUsed = 2
    Laptop_fixing = 3
    Laptop_overUsed = 4
    Laptop = (
        (Laptop_stock, 'لپ تاپ در انبار'),
        (Laptop_inUsed, 'لپ تاپ نزد کاربر'),
        (Laptop_fixing, 'لپ تاپ در تعمیرگاه'),
        (Laptop_overUsed, ' اسقاط شده است'),
    )
    Laptop_status = models.IntegerField(choices=Laptop, verbose_name='Laptop Status')
    Laptop_Description = models.TextField(verbose_name='Description', null=True)
    laptop_check_labled = models.BooleanField(verbose_name='Labled', default=False)

    def __str__(self):
        return "%s : %s " % (self.id, self.model)


class Personals(models.Model):
    class Meta:
        verbose_name = 'Personals'
        verbose_name_plural = 'Personals'

    id = models.CharField(verbose_name='Personal ID', max_length=30, primary_key=True)
    firstname = models.CharField(verbose_name='First name', max_length=30)
    lastname = models.CharField(verbose_name='Last name', max_length=30)
    email = models.EmailField(verbose_name='Email')
    telphone = models.IntegerField(verbose_name='Telephone')
    photo = models.ImageField(verbose_name='Images', upload_to='staff_photo/', blank=True)
    Department = models.CharField(verbose_name='Department', max_length=30, null=True, blank=True)

    def __str__(self):
        return "%s : %s %s" % (self.id, self.firstname, self.lastname)


class Owner(models.Model):
    owner_id = models.IntegerField(default=0, editable=False, primary_key=True)

    def owner_id(self):
        """
        Counts the total number of live changes of this type and saves the result to the `change_count` field.
        """
        count = self.change_set.filter(is_public=True).count()
        self.change_count = count
        self.save()

    Personal_id = models.ForeignKey(Personals, verbose_name='Personal ID', on_delete=PROTECT)
    owner_asset_1 = models.ForeignKey(Laptops, related_name='Asset1', verbose_name='Asset 1', blank=True, null=True,
                                      on_delete=PROTECT)
    owner_asset_2 = models.ForeignKey(Laptops, related_name='Asset2', verbose_name='Asset 2', blank=True, null=True,
                                      on_delete=PROTECT)
    owner_asset_3 = models.ForeignKey(Laptops, related_name='Asset3', verbose_name='Asset 3', blank=False,
                                      on_delete=PROTECT)

    def __str__(self):
        return "%s" % self.Personal_id

Assets/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from httplib import HTTPResponse
from urllib2 import HTTPRedirectHandler

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.serializers import json
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from pip._vendor.urllib3 import HTTPResponse

from Assets.models import Laptops, Personals, Owner


def tables_laptop_view(request):
    if request.user.is_authenticated:
        auth_user = request.user
        laptops = Laptops.objects.all()
        laptops_context = {

            'laptops': laptops,
            'auth_user': auth_user
        }
        return render(request, 'laptops_tables.html', context=laptops_context)
    else:
        return render(request, '404_not_found.html')


def tables_staffs_view(request):
    if request.user.is_authenticated:
        auth_user = request.user
        staffs = Personals.objects.all()
        staffs_context = {
            'staffs': staffs,
            'auth_user': auth_user
        }
        return render(request, 'Staffs_tables.html', context=staffs_context)
    else:
        return render(request, '404_not_found.html')


@login_required
def dashboard_view(request):
    auth_user = request.user
    staffs = Personals.objects.all()
    staffs_len = len(staffs)
    laptop_all = Laptops.objects.all()
    laptop_st_1 = Laptops.objects.filter(Laptop_status=1)
    laptop_st_2 = Laptops.objects.filter(Laptop_status=2)
    laptop_st_3 = Laptops.objects.filter(Laptop_status=3)
    laptop_st_4 = Laptops.objects.filter(Laptop_status=4)
    laptop_st_1_len = len(laptop_st_1)
    laptop_st_2_len = len(laptop_st_2)
    laptop_st_3_len = len(laptop_st_3)
    laptop_st_4_len = len(laptop_st_4)
    laptop_st_total_count = {
        'laptop_st_1_count': laptop_st_1_len,
        'laptop_st_2_count': laptop_st_2_len,
        'laptop_st_3_count': laptop_st_3_len,
        'laptop_st_4_count': laptop_st_4_len,
        'staffs_len': staffs_len,
        'laptops': laptop_all,
        'auth_user': auth_user,
    }

    return render(request, 'dashboard.html', context=laptop_st_total_count)


def tables_owners_view(request):
    if request.user.is_authenticated:
        auth_user = request.user
        owner = Owner.objects.all()
        owner_context = {
            'owners': owner,
            'auth_user': auth_user
        }
        return render(request, 'Owners_tables.html', owner_context)
    else:
        return render(request, '404_not_found.html')


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is None:
            raise Http404("User or Password is incorrect Please try again")
        else:
            login(request, user)
            return redirect('dashboard_view')
    else:
        return render(request, 'login.html')


def logout_view(request):
    logout(request)
    return render(request, 'log_out_successfully.html')

Assets/templates/404_not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<link href="{% static '404_not_found/bootstrap.min.css' %}" rel="stylesheet"
      id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!</h1>
                <h2>
                    404 Not Found</h2>
                <div class="error-details">
                    Sorry, an error has occured, Requested page not found!
                </div>
                <div class="error-actions">
                    <a href="{% url 'login_view' %}" class="btn btn-outline-dark "><span
                            class="glyphicon glyphicon-home"></span>
                        Please login
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

Assets/templates/laptops_tables.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Laptops's Table</title>

    <!-- Custom fonts for this template -->
    <link href="{% static 'fontawesome/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laptop-house"></i>
            </div>
            <div class="sidebar-brand-text mx-3">IT Admin</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard_view' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            Views
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link " href="{% url 'table_staffs_view' %}">
                <i class="fas fa-fw fa-user"></i>
                <span>Staffs</span>
            </a>
        </li>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'table_owners_view' %}">
                <i class="fas fa-fw fa-user-friends"></i>
                <span>Owners</span></a>
        </li>

        <!-- Nav Item - Tables -->
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'table_laptops_view' %}">
                <i class="fas fa-fw fa-laptop"></i>
                <span>Laptops</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <form class="form-inline">
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                </form>

                <!-- Topbar Search -->
                <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                               aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                    <li class="nav-item dropdown no-arrow d-sm-none">
                        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-search fa-fw"></i>
                        </a>
                        <!-- Dropdown - Messages -->
                        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                             aria-labelledby="searchDropdown">
                            <form class="form-inline mr-auto w-100 navbar-search">
                                <div class="input-group">
                                    <input type="text" class="form-control bg-light border-0 small"
                                           placeholder="Search for..." aria-label="Search"
                                           aria-describedby="basic-addon2">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fas fa-search fa-sm"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </li>


                    <div class="topbar-divider d-none d-sm-block"></div>

                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ auth_user }}</span>
                            <img class="img-profile rounded-circle" src="/media/profile.png">
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                             aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                Profile
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout_view' %}">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Logout
                            </a>
                        </div>
                    </li>

                </ul>

            </nav>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!-- Page Heading -->
                <h1 class="h3 mb-2 text-gray-800">Laptops View </h1>
                <p class="mb-4">IT Assets Explorer help you to manage everything.</p>

                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Laptop ID</th>
                                    <th>Model</th>
                                    <th>RAM</th>
                                    <th>Hard</th>
                                    <th>Windows</th>
                                    <th>Status</th>
                                    <th>Description</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th style="align-items: center">Laptop ID</th>
                                    <th>Model</th>
                                    <th>RAM</th>
                                    <th>Hard</th>
                                    <th>Windows</th>
                                    <th>Status</th>
                                    <th>Description</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% if laptops %}
                                    {% for laptop in laptops %}
                                        <tr>
                                            <td>{{ laptop.id }}</td>
                                            <td>{{ laptop.model }}</td>
                                            <td>{{ laptop.ram }}</td>
                                            <td>{{ laptop.get_HDD_status_display }}</td>
                                            <td>{{ laptop.get_Win_status_display }}</td>
                                            <td
                                                    {% if laptop.Laptop_status == laptop.Laptop_fixing %}
                                                        bgcolor="#ffa07a"
                                                    {% endif %}
                                                    {% if laptop.Laptop_status == laptop.Laptop_inUsed %}
                                                        bgcolor="#ffa07a"
                                                    {% endif %}
                                                    {% if laptop.Laptop_status == laptop.Laptop_overUsed %}
                                                        bgcolor="#d77500"
                                                    {% endif %}
                                                    {% if laptop.Laptop_status == laptop.Laptop_stock %}
                                                        bgcolor="#98ed00"
                                                    {% endif %}
                                                        {}
                                            >
                                                {{ laptop.get_Laptop_status_display }}
                                            </td>
                                            <td>{{ laptop.Laptop_Description }}</td>
                                        </tr>
                                    {% endfor %}
                                {% endif %}


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; Plazmid.Co 2020</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>

</body>

</html>

Assets/templates/log_out_successfully.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<link href="{% static '404_not_found/bootstrap.min.css' %}" rel="stylesheet"
      id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    See you soon :)</h1>
                <h2>
                    You have logged out successfully</h2>
                <div class="error-details">
                </div>
                <div class="error-actions">
                    <a href="{% url 'login_view' %}" class="btn btn-outline-dark "><span
                            class="glyphicon glyphicon-home"></span>
                        login again ?
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

Assets/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Login Page</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login_page/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'login_page/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'login_page/fonts/iconic/css/material-design-iconic-font.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login_page/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login_page/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login_page/vendor/animsition/css/animsition.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login_page/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login_page/vendor/daterangepicker/daterangepicker.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'login_page/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login_page/css/main.css' %}">
    <!--===============================================================================================-->
</head>
<body>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <form class="login100-form validate-form" method="post" action="dashboard.html">
                {% csrf_token %}

                <span class="login100-form-title p-b-26">
						Welcome
					</span>

                <div class="wrap-input100 validate-input" data-validate="Valid Username is: your AD User">
                    <input class="input100" type="text" name="username">
                    <span class="focus-input100" data-placeholder="Username"></span>
                </div>

                <div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
                    <input class="input100" type="password" name="password">
                    <span class="focus-input100" data-placeholder="Password"></span>
                </div>

                <div class="container-login100-form-btn">
                    <div class="wrap-login100-form-btn">
                        <div class="login100-form-bgbtn"></div>
                        <button class="login100-form-btn">
                            Login
                        </button>
                    </div>
                </div>

                <div class="text-center">
						<span class="txt1">
							Don’t have an account?
						</span>
                    <br>

                    <span class="txt1">
                        Please Contact administrator
                    </span>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
<script src="{% static 'login_page/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'login_page/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'login_page/vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'login_page/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'login_page/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'login_page/vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'login_page/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'login_page/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'login_page/js/main.js' %}"></script>
</body>
</html>